Models/Bowler.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Models
{
    public class Bowler
    {
        [Key]
        [Required]
        public int BowlerID { get; set; }
        [Required]
        public string BowlerLastName { get; set; }
        [Required]
        public string BowlerFirstName { get; set; }
        public string BowlerMiddleInit { get; set; }
        [Required]
        public string BowlerAddress { get; set; }
        [Required]
        public string BowlerCity { get; set; }
        [Required]
        [MaxLength(2)]
        public string BowlerState { get; set; }
        [Required]
        public string BowlerZip { get; set; }
        [Required]
        public string BowlerPhoneNumber { get; set; }

        public int TeamID { get; set; }
        public Team Team { get; set; }
    }
}

Models/BowlingDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Models
{
    public class BowlingDbContext : DbContext
    {
        public BowlingDbContext(DbContextOptions<BowlingDbContext> options) : base(options)
        {

        }

        public DbSet<Bowler> Bowlers { get; set; }
        public DbSet<Team> Teams { get; set; }
    }
}

Models/EFBowlersRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Models
{
    public class EFBowlersRepository : IBowlersRepository
    {
        private BowlingDbContext _context { get; set; }
        public EFBowlersRepository(BowlingDbContext temp)
        {
            _context = temp;
        }

        public IQueryable<Bowler> Bowlers => _context.Bowlers;
        public IQueryable<Team> Teams => _context.Teams;


        //fix all of these methods
        public void AddBowler(Bowler b)
        {
            _context.Add(b);
            _context.SaveChanges();
        }

        public void SaveBowler(Bowler b)
        {
            _context.Update(b);
            _context.SaveChanges();
        }

        public void DeleteBowler(Bowler b)
        {
            _context.Remove(b);
            _context.SaveChanges();

        }
    }
}

Models/IBowlersRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Models
{
    public interface IBowlersRepository
    {
        IQueryable<Bowler> Bowlers { get; }
        IQueryable<Team> Teams { get; }

        public void AddBowler(Bowler b);
        public void SaveBowler(Bowler b);
        public void DeleteBowler(Bowler b);


    }
}

Models/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Models
{
    public class Team
    {
        [Key]
        [Required]
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public int CaptainID { get; set; }

    }
}

Components/TeamsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission13.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Views.Shared.Components
{
    public class TeamsViewComponent : ViewComponent
    {
        private IBowlersRepository repo { get; set; }

        public TeamsViewComponent (IBowlersRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {

            ViewBag.SelectedTeam = RouteData?.Values["teamName"];

            //var cats = repo.Books
            //    .Select(x => x.Category)
            //    .Distinct()
            //    .OrderBy(x => x);
            var teams = repo.Teams
                .Select(x => x.TeamName)
                //.Distinct()
                .OrderBy(x => x);

            //IEnumerable<Team> teams = repo.Teams.ToList();


            return View(teams);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Mission13.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Controllers
{
    public class HomeController : Controller
    {
        private IBowlersRepository _repo { get; set; }


        //private BowlingDbContext _context { get; set; }
        // IBowlersRepository temp
        // _repo = temp


        public HomeController(IBowlersRepository temp)
        {
            _repo = temp;
        }

        public IActionResult Index(string teamName)
        {

            ViewBag.header = teamName;
            ViewBag.tester = "test";
            var blah = _repo.Bowlers
                .Include(x => x.Team)
                .Where(x => x.Team.TeamName == teamName || teamName == null)
                //Use && for and || is or
                //.FromSqlRaw("SELECT * FROM bowlers")
                .ToList();


            return View(blah);
        }

        [HttpGet]
        public IActionResult AddBowler()
        {
            ViewBag.Teams = _repo.Teams.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult AddBowler(Bowler b)
        {
            if (ModelState.IsValid)
            {

            int maxID = _repo.Bowlers.Max(u => u.BowlerID);
            b.BowlerID = maxID + 1;
            _repo.AddBowler(b);
            return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Teams = _repo.Teams.ToList();
                return View(b);
            }




        }

        [HttpGet]
        public IActionResult Edit(int BowlerID)
        {
            ViewBag.Teams = _repo.Teams.ToList();
            Bowler bowler = _repo.Bowlers
                .Single(x => x.BowlerID == BowlerID);

            return View("AddBowler", bowler);
        }

        [HttpPost]

        public IActionResult Edit(Bowler b)
        {
            _repo.SaveBowler(b);
            return RedirectToAction("Index");
        }


        public IActionResult Delete(int BowlerID)
        {
            Bowler bowler = _repo.Bowlers.Single(x => x.BowlerID == BowlerID);

            _repo.DeleteBowler(bowler);
            return RedirectToAction("Index");

        }

    }
}

Views/Home/AddBowler.cshtml
@{
}

@model Mission13.Models.Bowler

<h1>Bowler Form</h1>
<form method="post">

    <div class="text-danger" asp-validation-summary="All"></div>

    <label asp-for="BowlerFirstName">First Name:</label>
    <input asp-for="BowlerFirstName" />
    <br />
    <label asp-for="BowlerMiddleInit">Middle Initial:</label>
    <input asp-for="BowlerMiddleInit" placeholder="Optional" />
    <br />
    <label asp-for="BowlerLastName">Last Name:</label>
    <input asp-for="BowlerLastName" />
    <br />
    <label asp-for="BowlerAddress">Address:</label>
    <input asp-for="BowlerAddress" />
    <br />
    <label asp-for="BowlerCity">City:</label>
    <input asp-for="BowlerCity" />
    <br />
    <label asp-for="BowlerState">State:</label>
    <input asp-for="BowlerState" />
    <br />
    <label asp-for="BowlerZip">Zip Code:</label>
    <input asp-for="BowlerZip" />
    <br />
    <label asp-for="BowlerPhoneNumber">Phone Number:</label>
    <input asp-for="BowlerPhoneNumber" />
    <br />
    <label asp-for="TeamID">Team:</label>
    <select asp-for="TeamID">
        <option value="">Select a Team</option>
        @foreach (Team t in ViewBag.Teams)
        {
            <option value="@t.TeamID">@t.TeamName</option>
        }

    </select>
    <br />

    <button type="submit">Submit Application</button>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<Bowler>



<div class="row">
    <div class="col-2">
        <vc:teams></vc:teams>
    </div>
    <div class="col-10">
        <h1>
            @ViewBag.header Bowlers: @ViewBag.tester
        </h1>
        <table class="table table-bordered table-striped" style="font-size:.9rem;">

            <thead class="font-weight-bold">
                <tr>
                    <td>First Name</td>
                    <td style="width:50px;">Middle Initial</td>
                    <td>Last Name</td>
                    <td>Address</td>
                    <td>City</td>
                    <td>State</td>
                    <td>Zip Code</td>
                    <td>Phone Number</td>
                    <td colspan="2"><a class="btn btn-primary" asp-controller="Home" asp-action="AddBowler">New Bowler</a></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var b in Model)
                {
                    <tr>
                        <td>@b.BowlerFirstName</td>
                        <td>@b.BowlerMiddleInit</td>
                        <td>@b.BowlerLastName</td>
                        <td>@b.BowlerAddress</td>
                        <td>@b.BowlerCity</td>
                        <td>@b.BowlerState</td>
                        <td>@b.BowlerZip</td>
                        <td>@b.BowlerPhoneNumber</td>
                        @*<td>@b.Team.TeamName</td>*@

                        <td><a asp-controller="Home" asp-action="Edit" asp-route-bowlerid="@b.BowlerID">Edit</a></td>
                        <td><a asp-controller="Home" asp-action="Delete" asp-route-bowlerid="@b.BowlerID">Delete</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-2">
        
    </div>
    <div class="col-10">

    </div>

</div>

Views/Shared/Components/Teams/Default.cshtml
@{
}

@model IEnumerable<string>

<div class="d-grid gap-2" style="display:grid; justify-items:stretch;">
    <a class="btn btn-outline-primary" asp-controller="Home" asp-action="Index" asp-route-teamName="">Home</a>


    @foreach (string t in Model)
    {
        <a class="btn @(ViewBag.SelectedTeam == t ? "btn-primary" : "btn-outline-primary")" asp-controller="Home" asp-action="Index" asp-route-teamName="@t">@t</a>
    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mission13</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mission13</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Mission13 - Josh Gardner  
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>